//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://example.com/aservice", ConfigurationName = "AServicePortType")]
    public interface AServicePortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://example.com/aservice/GetANames", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<GetANamesResponse> GetANamesAsync(GetANamesRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://example.com/aservice")]
    public partial class GetAHeader
    {

        private string requestorField;

        private string requestDateTimeField;

        private string callingContextField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string requestor
        {
            get
            {
                return this.requestorField;
            }
            set
            {
                this.requestorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string requestDateTime
        {
            get
            {
                return this.requestDateTimeField;
            }
            set
            {
                this.requestDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string callingContext
        {
            get
            {
                return this.callingContextField;
            }
            set
            {
                this.callingContextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://example.com/aservice")]
    public partial class GetAFilter
    {

        private bool includeNamesField;

        private bool includeTreesField;

        private bool includeRoadsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool includeNames
        {
            get
            {
                return this.includeNamesField;
            }
            set
            {
                this.includeNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool includeTrees
        {
            get
            {
                return this.includeTreesField;
            }
            set
            {
                this.includeTreesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool includeRoads
        {
            get
            {
                return this.includeRoadsField;
            }
            set
            {
                this.includeRoadsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://example.com/aservice")]
    public partial class GetAResponseCategory
    {

        private string categoryNameField;

        private string[] nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string CategoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", Order = 1)]
        public string[] Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetARequest", WrapperNamespace = "http://example.com/aservice", IsWrapped = true)]
    public partial class GetANamesRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://example.com/aservice", Order = 0)]
        public GetAHeader header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://example.com/aservice", Order = 1)]
        public GetAFilter filter;

        public GetANamesRequest()
        {
        }

        public GetANamesRequest(GetAHeader header, GetAFilter filter)
        {
            this.header = header;
            this.filter = filter;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetAResponse", WrapperNamespace = "http://example.com/aservice", IsWrapped = true)]
    public partial class GetANamesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://example.com/aservice", Order = 0)]
        public GetAHeader header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://example.com/aservice", Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable = false)]
        public GetAResponseCategory[] Names;

        public GetANamesResponse()
        {
        }

        public GetANamesResponse(GetAHeader header, GetAResponseCategory[] Names)
        {
            this.header = header;
            this.Names = Names;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AServicePortTypeChannel : AServicePortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AServicePortTypeClient : System.ServiceModel.ClientBase<AServicePortType>, AServicePortType
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public AServicePortTypeClient() :
                base(AServicePortTypeClient.GetDefaultBinding(), AServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AServicePortTypeClient(EndpointConfiguration endpointConfiguration) :
                base(AServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), AServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(AServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(AServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<GetANamesResponse> GetANamesAsync(GetANamesRequest request)
        {
            return base.Channel.GetANamesAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7800/api/AService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.AServicePort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.AServicePort);
        }

        public enum EndpointConfiguration
        {

            AServicePort,
        }
    }
}